### ISSUE TITLE
Fix presentation on generic pages

### ISSUE THREAD

**Issue by pwalsh** [okfn/opentrials-ebola-tracker#31]
# Description

Generic pages (access page, 404s) look messy.

# Tasks

* [x] Sticky footer for pages with little content
* [x] Ensure content is in the content area (i.e.: left aligned with content in headers and footers)
* [x] Ensure that the access code entry looks reasonable

**Comment by pwalsh** [comment]
Don't see sticky footer, nor fix for content in content area.

Example:

<img width="1280" alt="screenshot 2015-10-25 10 48 46" src="https://cloud.githubusercontent.com/assets/791678/10714766/1247aee4-7b06-11e5-9019-9cc784208ec9.png">
