### ISSUE TITLE
New ui and data enhancements

### ISSUE THREAD

**Issue by pwalsh** [okfn/opentrials-ebola-tracker#42]
# Description

Some additional requests for changes to ui and data.

# Tasks

* [x] In the leaderboard, introduce a new color, amber, for trials that have a publication delay of 150 days or less (so, instead of red, these will be amber)
* [x] Display the deaths on the graph in quarterly steps, so:
  * [x] Scale from {beginning to 2014 stays the same}
  * [x] Scale from 2014 to {present} steps up in yearly quarters
* [x] Truncated texts in the leaderboard blocks - fix these sections paragraphs at 2 lines and not truncate at one, so that we can get the whole text
* [x] bold for "Sponsored by:" and "Principal investigator:" in the leaderboard blocks
* [x] Clicking the Trial ID number should link to the trial page itself (target blank, each trial has a URL property)
* [x] Small button/label after or next to the "no results have been published" line at bottom of each leaderboard block which is a mailto: link:
  * [x] Text: "Submit information on this trial"
  * [x] mailto subject line: "Submission of information on Trial ID {trialID} from the Ebola Trials Tracker"
  * [x] use same email address as the "something missing" link from the header
* [x] <del>Updates to texts - TBC - *requires* texts to the supplied first</del> Ben did not deliver.
