### ISSUE TITLE
Prepare app for partners to use

### ISSUE THREAD

**Issue by pwalsh** [okfn/opentrials-ebola-tracker#45]
# Description

We need to host the ebola tracker under our own domain in a modified form for the coming weeks. This enables partners to get a look at the "landing page", while preventing publication of some of the data before time.

# Tasks

* [x] Add a new ENV VAR `DISABLE_LEADERBOOARD`
* [x] When `DISABLE_LEADERBOARD` is `true`, Then, completely remove the whole leaderboard section from the app: it can never appear when true.
* [x] Add a test for the disable feature

**Comment by pwalsh** [comment]
DONE
